### ISSUE TITLE
edge.width() returns weight, not width/thickness

### ISSUE THREAD

**Issue by frex-e** [ehne/PyNode-Next#37]
As described in title.
 
Issue exits in edge.py, on line 122.

```python
    def width(self):
        """Returns the thickness of the edge."""
        return self._weight
```

#### Proposed solution
Replace `self._weight` with `self._thickness`

Also maybe make the naming more consistent? Width is called both thickness and width. And in the edge.set_width() function, the parameter is called weight which makes things confusing and might've led to this issue.

Later today when I've got time i'll submit a pull request.

**Comment by ehne** [comment]
This issue should be fixed. And internally all references to width are now just `width`, and not sometimes `thickness`. 

 Changing the name to "thickness" across the board may be something useful to do with v3, as usage of the term "width" can clash with how weights are sometimes used in Algorithmics.
