### ISSUE TITLE
Overflowing node text becomes invisible on background.

### ISSUE THREAD

**Issue by ehne** [ehne/PyNode-Next#7]
When the node's value becomes larger than the circle can contain, it becomes hard to read the text, as it is a very similar colour to the background colour.

The original PyNode solved this by having outlines on the text. Algorithm X doesn't seem to support this kind of thing, so it might need to be implemented with external d3 stuff in ui.html.

Alternatively, the nodes could dynamically size to fit the text in (like they do in GraphX). Although, this would most likely remove the nice circle shape and would mean that the `size` property would be basically useless as the nodes would not have one consistent size.

**Comment by mipy1** [comment]
How about resizing the text? This would only work up to a point though, where it would become unreadable.
